<div class="global-wrapper">

<div class="canvas" id="canvas">

<script type="text/javascript">
    /*$(function(){
     if(window.sessionStorage){
     if(!sessionStorage.getItem('topBar')){
     sessionStorage.setItem("topBar",1);
     }

     if(sessionStorage.getItem('topBar') != 0){
     $("#canvas").addClass("canvas-topbar-show");
     }else{
     $("#canvas").removeClass("canvas-topbar-show");
     }
     }

     $("#close-top-bar").on("click",function(){
     console.log("click");
     $(this).parents("#canvas").removeClass("canvas-topbar-show");
     sessionStorage.setItem('topBar', 0);
     });
     });*/
</script>
<div class="js-top-banner js-top-banner-hide">
    <a href="">
        <img src="" alt="Patpat Image"></a>
    <i></i>
    <span></span>
</div>
<header id="site-header">


<div class="header-top" id="patpat-header-country">
<div class="container">
<div class="row hidden-xs">
<div class="col-xs-4">

<div class="site-header-left hidden-xs">
    <div class="site-header-language">
<span>English
</span>

        <div id="edit-info-language-selector">
            <ul>
                <li data-name="en" data-url="http://www.patpat.com/">English</li>
                <li data-name="ar" data-url="http://ar.patpat.com/"> العربية</
                ></li>
            </ul>
        </div>
    </div>
    <div class="site-header-left-dots">•</div>
    <div class="site-header-currency">
        <span class="currency-show-selector">USD</span>

        <div id="edit-info-currency-selector">
            <ul>
                <li class="select_currency" data-code="USD">
                    USD
                </li>
                <li class="select_currency" data-code="EUR">
                    EUR
                </li>
                <li class="select_currency" data-code="GBP">
                    GBP
                </li>
                <li class="select_currency" data-code="AUD">
                    AUD
                </li>
                <li class="select_currency" data-code="AED">
                    AED
                </li>
                <li class="select_currency" data-code="BDT">
                    BDT
                </li>
                <li class="select_currency" data-code="CAD">
                    CAD
                </li>
                <li class="select_currency" data-code="IDR">
                    IDR
                </li>
                <li class="select_currency" data-code="ILS">
                    ILS
                </li>
                <li class="select_currency" data-code="INR">
                    INR
                </li>
                <li class="select_currency" data-code="JOD">
                    JOD
                </li>
                <li class="select_currency" data-code="KWD">
                    KWD
                </li>
                <li class="select_currency" data-code="LKR">
                    LKR
                </li>
                <li class="select_currency" data-code="MXN">
                    MXN
                </li>
                <li class="select_currency" data-code="MYR">
                    MYR
                </li>
                <li class="select_currency" data-code="NZD">
                    NZD
                </li>
                <li class="select_currency" data-code="PHP">
                    PHP
                </li>
                <li class="select_currency" data-code="PLN">
                    PLN
                </li>
                <li class="select_currency" data-code="RUB">
                    RUB
                </li>
                <li class="select_currency" data-code="SAR">
                    SAR
                </li>
                <li class="select_currency" data-code="SEK">
                    SEK
                </li>
                <li class="select_currency" data-code="SGD">
                    SGD
                </li>
                <li class="select_currency" data-code="THB">
                    THB
                </li>
                <li class="select_currency" data-code="UAH">
                    UAH
                </li>
            </ul>
        </div>
        <form id="change_currency" method="post" action="/changeCurrency">
            <input type="hidden" name="_token" value="CvbgcAQwvjJAPOS289tLg0AVbsZr64wtY5G7wkOB"/>
            <input type="hidden" name="url" value="http://www.patpat.com"/>
            <input type="hidden" name="currency_iso_code" id="currency_iso_code" value="USD"/>
        </form>
    </div>
    <div class="site-header-left-dots">•</div>
    <div class="site-header-country">
                        <span class="country-show-selector"><img
                                src="https://img.patpat.com/national_flag/58eb6beda1e35/1491823597.png" alt=""/>  United States</span>

        <div id="edit-info-country-selector">
            <i class="tit">SHIPPING TO</i>
            <ul class="choice-country">

            </ul>
        </div>
        <form id="change_country" method="post" action="/changeCountry">
            <input type="hidden" name="_token" value="CvbgcAQwvjJAPOS289tLg0AVbsZr64wtY5G7wkOB"/>
            <input type="hidden" name="url" value="http://www.patpat.com"/>
            <input type="hidden" name="country_abbreviation" id="country_abbreviation" value="US"/>
        </form>
    </div>
</div>

<script type="text/javascript">
$(".select_currency").click(function () {
    var iso_code = $(this).data('code');
    console.log(iso_code);
    $("#currency_iso_code").val(iso_code);
    $("#change_currency").submit();
});

//监听语言切换
$("#edit-info-language-selector li").click(function () {
    var _this = this;
    $.get('/set-language', {language: $(this).data('name')}, function () {
        window.location.href = $(_this).data('url');
    });
});

/*头部国家选择----------start*/
/*异步加载国家*/
var choiceCountry = $(".choice-country");
var countryHtml = '';
var countrys = [{
    "id": 1,
    "country_name": "United States",
    "country_abbreviation": "US",
    "iso_code": "USD",
    "symbol_display": "$",
    "national_flag": "https:\/\/img.patpat.com\/national_flag\/58eb6beda1e35\/1491823597.png"
}, {
    "id": 2,
    "country_name": "United Kingdom",
    "country_abbreviation": "GB",
    "iso_code": "GBP",
    "symbol_display": "\u00a3",
    "national_flag": "https:\/\/img.patpat.com\/national_flag\/58eb6c3135922\/1491823665.png"
}, {
    "id": 16,
    "country_name": "Italy",
    "country_abbreviation": "IT",
    "iso_code": "EUR",
    "symbol_display": "\u20ac",
    "national_flag": "https:\/\/img.patpat.com\/national_flag\/58eb6d759eb56\/1491823989.png"
}, {
    "id": 4,
    "country_name": "Australia",
    "country_abbreviation": "AU",
    "iso_code": "AUD",
    "symbol_display": "AUD",
    "national_flag": "https:\/\/img.patpat.com\/national_flag\/58eb6c7389f2b\/1491823731.png"
}, {
    "id": 6,
    "country_name": "Germany",
    "country_abbreviation": "DE",
    "iso_code": "EUR",
    "symbol_display": "\u20ac",
    "national_flag": "https:\/\/img.patpat.com\/national_flag\/58eb6cc142a69\/1491823809.png"
}, {
    "id": 38,
    "country_name": "Argentina",
    "country_abbreviation": "AR",
    "iso_code": "USD",
    "symbol_display": "$",
    "national_flag": "https:\/\/img.patpat.com\/national_flag\/58eb28763c354\/1491806326.png"
}, {
    "id": 39,
    "country_name": "Austria",
    "country_abbreviation": "AT",
    "iso_code": "EUR",
    "symbol_display": "\u20ac",
    "national_flag": "https:\/\/img.patpat.com\/national_flag\/58eb2a8f35b62\/1491806863.png"
}, {
    "id": 40,
    "country_name": "Belarus",
    "country_abbreviation": "BY",
    "iso_code": "USD",
    "symbol_display": "$",
    "national_flag": "https:\/\/img.patpat.com\/national_flag\/58eb2d5d37e6c\/1491807581.png"
}, {
    "id": 9,
    "country_name": "Belgium",
    "country_abbreviation": "BE",
    "iso_code": "EUR",
    "symbol_display": "\u20ac",
    "national_flag": "https:\/\/img.patpat.com\/national_flag\/58eb6ce75d173\/1491823847.png"
}, {
    "id": 30,
    "country_name": "Bengal",
    "country_abbreviation": "BD",
    "iso_code": "BDT",
    "symbol_display": "BDT",
    "national_flag": "https:\/\/img.patpat.com\/national_flag\/58eb6e8a142e4\/1491824266.png"
}, {
    "id": 41,
    "country_name": "Brazil",
    "country_abbreviation": "BR",
    "iso_code": "USD",
    "symbol_display": "$",
    "national_flag": "https:\/\/img.patpat.com\/national_flag\/58eb3542030a2\/1491809602.png"
}, {
    "id": 42,
    "country_name": "Bulgaria",
    "country_abbreviation": "BG",
    "iso_code": "USD",
    "symbol_display": "$",
    "national_flag": "https:\/\/img.patpat.com\/national_flag\/58eb3c235dfc4\/1491811363.png"
}, {
    "id": 3,
    "country_name": "Canada",
    "country_abbreviation": "CA",
    "iso_code": "CAD",
    "symbol_display": "CAD",
    "national_flag": "https:\/\/img.patpat.com\/national_flag\/58eb6c56cee3b\/1491823702.png"
}, {
    "id": 43,
    "country_name": "Croatia",
    "country_abbreviation": "HR",
    "iso_code": "USD",
    "symbol_display": "$",
    "national_flag": "https:\/\/img.patpat.com\/national_flag\/58eb415f2af3f\/1491812703.png"
}, {
    "id": 44,
    "country_name": "Cyprus",
    "country_abbreviation": "CY",
    "iso_code": "EUR",
    "symbol_display": "\u20ac",
    "national_flag": "https:\/\/img.patpat.com\/national_flag\/58eb456aa290f\/1491813738.png"
}, {
    "id": 45,
    "country_name": "Czech Republic",
    "country_abbreviation": "CZ",
    "iso_code": "USD",
    "symbol_display": "$",
    "national_flag": "https:\/\/img.patpat.com\/national_flag\/58eb45c301c2d\/1491813827.png"
}, {
    "id": 46,
    "country_name": "Denmark",
    "country_abbreviation": "DK",
    "iso_code": "USD",
    "symbol_display": "$",
    "national_flag": "https:\/\/img.patpat.com\/national_flag\/58eb47b7578e8\/1491814327.png"
}, {
    "id": 47,
    "country_name": "Egypt",
    "country_abbreviation": "EG",
    "iso_code": "USD",
    "symbol_display": "$",
    "national_flag": "https:\/\/img.patpat.com\/national_flag\/58eb4844b11da\/1491814468.png"
}, {
    "id": 48,
    "country_name": "Estonia",
    "country_abbreviation": "EE",
    "iso_code": "EUR",
    "symbol_display": "\u20ac",
    "national_flag": "https:\/\/img.patpat.com\/national_flag\/58eb489507e99\/1491814549.png"
}, {
    "id": 49,
    "country_name": "Finland",
    "country_abbreviation": "FI",
    "iso_code": "EUR",
    "symbol_display": "\u20ac",
    "national_flag": "https:\/\/img.patpat.com\/national_flag\/58eb48e2a0afc\/1491814626.png"
}, {
    "id": 7,
    "country_name": "France",
    "country_abbreviation": "FR",
    "iso_code": "EUR",
    "symbol_display": "\u20ac",
    "national_flag": "https:\/\/img.patpat.com\/national_flag\/58eb6cd626b72\/1491823830.png"
}, {
    "id": 50,
    "country_name": "Greece",
    "country_abbreviation": "GR",
    "iso_code": "EUR",
    "symbol_display": "\u20ac",
    "national_flag": "https:\/\/img.patpat.com\/national_flag\/58eb490de44e0\/1491814669.png"
}, {
    "id": 51,
    "country_name": "Hong Kong",
    "country_abbreviation": "HK",
    "iso_code": "USD",
    "symbol_display": "$",
    "national_flag": "https:\/\/img.patpat.com\/national_flag\/58eb55eeea5a7\/1491817966.png"
}, {
    "id": 52,
    "country_name": "Hungary",
    "country_abbreviation": "HU",
    "iso_code": "USD",
    "symbol_display": "$",
    "national_flag": "https:\/\/img.patpat.com\/national_flag\/58eb5a1401867\/1491819028.png"
}, {
    "id": 20,
    "country_name": "India",
    "country_abbreviation": "IN",
    "iso_code": "INR",
    "symbol_display": "INR",
    "national_flag": "https:\/\/img.patpat.com\/national_flag\/58eb6dffd4033\/1491824127.png"
}, {
    "id": 23,
    "country_name": "Indonesia",
    "country_abbreviation": "ID",
    "iso_code": "IDR",
    "symbol_display": "IDR",
    "national_flag": "https:\/\/img.patpat.com\/national_flag\/58eb6e0e52761\/1491824142.png"
}, {
    "id": 17,
    "country_name": "Ireland",
    "country_abbreviation": "IE",
    "iso_code": "EUR",
    "symbol_display": "\u20ac",
    "national_flag": "https:\/\/img.patpat.com\/national_flag\/58eb6dc7bbe6e\/1491824071.png"
}, {
    "id": 29,
    "country_name": "Israel",
    "country_abbreviation": "IL",
    "iso_code": "ILS",
    "symbol_display": "ILS",
    "national_flag": "https:\/\/img.patpat.com\/national_flag\/58eb6e72e6eaa\/1491824242.png"
}, {
    "id": 53,
    "country_name": "Japan",
    "country_abbreviation": "JP",
    "iso_code": "USD",
    "symbol_display": "$",
    "national_flag": "https:\/\/img.patpat.com\/national_flag\/58eb66d7d2d11\/1491822295.png"
}, {
    "id": 28,
    "country_name": "Jordan",
    "country_abbreviation": "JO",
    "iso_code": "JOD",
    "symbol_display": "JOD",
    "national_flag": "https:\/\/img.patpat.com\/national_flag\/58eb6e6301b11\/1491824227.png"
}, {
    "id": 27,
    "country_name": "Kuwait",
    "country_abbreviation": "KW",
    "iso_code": "KWD",
    "symbol_display": "KWD",
    "national_flag": "https:\/\/img.patpat.com\/national_flag\/58eb6e4ea4058\/1491824206.png"
}, {
    "id": 54,
    "country_name": "Latvia",
    "country_abbreviation": "LV",
    "iso_code": "EUR",
    "symbol_display": "\u20ac",
    "national_flag": "https:\/\/img.patpat.com\/national_flag\/58eb67c0be4b7\/1491822528.png"
}, {
    "id": 55,
    "country_name": "Lithuania",
    "country_abbreviation": "LT",
    "iso_code": "EUR",
    "symbol_display": "\u20ac",
    "national_flag": "https:\/\/img.patpat.com\/national_flag\/58eb680389e8f\/1491822595.png"
}, {
    "id": 56,
    "country_name": "Luxembourg",
    "country_abbreviation": "LU",
    "iso_code": "EUR",
    "symbol_display": "\u20ac",
    "national_flag": "https:\/\/img.patpat.com\/national_flag\/58eb684a19059\/1491822666.png"
}, {
    "id": 19,
    "country_name": "Malaysia",
    "country_abbreviation": "MY",
    "iso_code": "MYR",
    "symbol_display": "RM",
    "national_flag": "https:\/\/img.patpat.com\/national_flag\/58eb6deebd825\/1491824110.png"
}, {
    "id": 57,
    "country_name": "Malta",
    "country_abbreviation": "MT",
    "iso_code": "EUR",
    "symbol_display": "\u20ac",
    "national_flag": "https:\/\/img.patpat.com\/national_flag\/58eb68882183f\/1491822728.png"
}, {
    "id": 37,
    "country_name": "Mexico",
    "country_abbreviation": "MX",
    "iso_code": "MXN",
    "symbol_display": "MEX",
    "national_flag": "https:\/\/img.patpat.com\/national_flag\/58eb6f246e6ba\/1491824420.png"
}, {
    "id": 31,
    "country_name": "Netherlands",
    "country_abbreviation": "NL",
    "iso_code": "EUR",
    "symbol_display": "\u20ac",
    "national_flag": "https:\/\/img.patpat.com\/national_flag\/58eb6eac05949\/1491824300.png"
}, {
    "id": 5,
    "country_name": "New Zealand",
    "country_abbreviation": "NZ",
    "iso_code": "NZD",
    "symbol_display": "NZD",
    "national_flag": "https:\/\/img.patpat.com\/national_flag\/58eb6caacd364\/1491823786.png"
}, {
    "id": 58,
    "country_name": "Norway",
    "country_abbreviation": "NO",
    "iso_code": "USD",
    "symbol_display": "$",
    "national_flag": "https:\/\/img.patpat.com\/national_flag\/58eb69141e52a\/1491822868.png"
}, {
    "id": 59,
    "country_name": "Oman",
    "country_abbreviation": "OM",
    "iso_code": "USD",
    "symbol_display": "$",
    "national_flag": "https:\/\/img.patpat.com\/national_flag\/58eb698bd6268\/1491822987.png"
}, {
    "id": 25,
    "country_name": "Philippines",
    "country_abbreviation": "PH",
    "iso_code": "PHP",
    "symbol_display": "PHP",
    "national_flag": "https:\/\/img.patpat.com\/national_flag\/58eb6e32364d5\/1491824178.png"
}, {
    "id": 15,
    "country_name": "Poland",
    "country_abbreviation": "PL",
    "iso_code": "PLN",
    "symbol_display": "PLN",
    "national_flag": "https:\/\/img.patpat.com\/national_flag\/58eb6d656518d\/1491823973.png"
}, {
    "id": 12,
    "country_name": "Portugal",
    "country_abbreviation": "PT",
    "iso_code": "EUR",
    "symbol_display": "\u20ac",
    "national_flag": "https:\/\/img.patpat.com\/national_flag\/58eb6d2986677\/1491823913.png"
}, {
    "id": 60,
    "country_name": "Qatar",
    "country_abbreviation": "QA",
    "iso_code": "USD",
    "symbol_display": "$",
    "national_flag": "https:\/\/img.patpat.com\/national_flag\/58eb6a0b237c5\/1491823115.png"
}, {
    "id": 61,
    "country_name": "Romania",
    "country_abbreviation": "RO",
    "iso_code": "USD",
    "symbol_display": "$",
    "national_flag": "https:\/\/img.patpat.com\/national_flag\/58eb6a8811e8b\/1491823240.png"
}, {
    "id": 32,
    "country_name": "Russian Federation",
    "country_abbreviation": "RU",
    "iso_code": "RUB",
    "symbol_display": "RUB",
    "national_flag": "https:\/\/img.patpat.com\/national_flag\/58eb6ec010199\/1491824320.png"
}, {
    "id": 33,
    "country_name": "Saudi Arabia",
    "country_abbreviation": "SA",
    "iso_code": "SAR",
    "symbol_display": "SAR",
    "national_flag": "https:\/\/img.patpat.com\/national_flag\/58eb6ed592459\/1491824341.png"
}, {
    "id": 62,
    "country_name": "Serbia",
    "country_abbreviation": "RS",
    "iso_code": "USD",
    "symbol_display": "$",
    "national_flag": "https:\/\/img.patpat.com\/national_flag\/58eb6bc188987\/1491823553.png"
}, {
    "id": 18,
    "country_name": "Singapore",
    "country_abbreviation": "SG",
    "iso_code": "SGD",
    "symbol_display": "SGD",
    "national_flag": "https:\/\/img.patpat.com\/national_flag\/58eb6dd98e265\/1491824089.png"
}, {
    "id": 63,
    "country_name": "Slovakia",
    "country_abbreviation": "SK",
    "iso_code": "EUR",
    "symbol_display": "\u20ac",
    "national_flag": "https:\/\/img.patpat.com\/national_flag\/58ecb612bf350\/1491908114.png"
}, {
    "id": 64,
    "country_name": "Slovenia",
    "country_abbreviation": "SI",
    "iso_code": "USD",
    "symbol_display": "$",
    "national_flag": "https:\/\/img.patpat.com\/national_flag\/58ecb67e20c8c\/1491908222.png"
}, {
    "id": 68,
    "country_name": "South Africa",
    "country_abbreviation": "ZA",
    "iso_code": "USD",
    "symbol_display": "$",
    "national_flag": "https:\/\/img.patpat.com\/national_flag\/58ecbd4625e3b\/1491909958.png"
}, {
    "id": 11,
    "country_name": "Spain",
    "country_abbreviation": "ES",
    "iso_code": "EUR",
    "symbol_display": "\u20ac",
    "national_flag": "https:\/\/img.patpat.com\/national_flag\/58eb6d11c44fa\/1491823889.png"
}, {
    "id": 34,
    "country_name": "Sri Lanka",
    "country_abbreviation": "LKR",
    "iso_code": "LKR",
    "symbol_display": "LKR",
    "national_flag": "https:\/\/img.patpat.com\/national_flag\/58eb6eea61078\/1491824362.png"
}, {
    "id": 14,
    "country_name": "Sweden",
    "country_abbreviation": "SE",
    "iso_code": "SEK",
    "symbol_display": "SEK",
    "national_flag": "https:\/\/img.patpat.com\/national_flag\/58eb6d53aeede\/1491823955.png"
}, {
    "id": 65,
    "country_name": "Switzerland",
    "country_abbreviation": "CH",
    "iso_code": "USD",
    "symbol_display": "$",
    "national_flag": "https:\/\/img.patpat.com\/national_flag\/58ecb704cde48\/1491908356.png"
}, {
    "id": 66,
    "country_name": "Taiwan",
    "country_abbreviation": "TW",
    "iso_code": "USD",
    "symbol_display": "$",
    "national_flag": "https:\/\/img.patpat.com\/national_flag\/58ecb733476df\/1491908403.png"
}, {
    "id": 24,
    "country_name": "Thailand",
    "country_abbreviation": "TH",
    "iso_code": "THB",
    "symbol_display": "THB",
    "national_flag": "https:\/\/img.patpat.com\/national_flag\/58eb6e20ca060\/1491824160.png"
}, {
    "id": 67,
    "country_name": "Turkey",
    "country_abbreviation": "TR",
    "iso_code": "USD",
    "symbol_display": "$",
    "national_flag": "https:\/\/img.patpat.com\/national_flag\/58ecb76317c07\/1491908451.png"
}, {
    "id": 35,
    "country_name": "Ukraine",
    "country_abbreviation": "UA",
    "iso_code": "UAH",
    "symbol_display": "UAH",
    "national_flag": "https:\/\/img.patpat.com\/national_flag\/58eb6efd9d7b3\/1491824381.png"
}, {
    "id": 36,
    "country_name": "United Arab Emirates",
    "country_abbreviation": "AE",
    "iso_code": "AED",
    "symbol_display": "AED",
    "national_flag": "https:\/\/img.patpat.com\/national_flag\/58eb6f0eb3e87\/1491824398.png"
}];
var countrysLen = countrys.length;
$(".header-top .site-header-country").hover(function () {
    $(this).children("#edit-info-country-selector").show();
    if (choiceCountry.children().length == 0) {
        for (var i = 0; i < countrysLen; i++) {
            countryHtml += '<li  class="select_country" data-country_abbreviation="' + countrys[i].country_abbreviation + '">'
            + '<a>'
            + '<img src="' + countrys[i].national_flag + '">'
            + '<span>' + countrys[i].country_name + '</span>'
            + '</a>'
            + '</li>';
        }
        choiceCountry.append(countryHtml);
    }
    //$(this).addClass("on");
}, function () {
    $(this).children("#edit-info-country-selector").hide()
});

choiceCountry.delegate(".select_country", "click", function () {
    var country_abbreviation = $(this).data('country_abbreviation');
    $("#country_abbreviation").val(country_abbreviation);
    $("#change_country").submit();
});
</script>
<!-- language nav-->
</div>
<div class="col-xs-4">
    <div class="site-shipping font-regular">
        <!-- <a>FREE shipping for orders over $35.00</a> -->
    </div>
</div>
<div class="col-xs-4">
    <div class="site-header-right">
        <a href="guest/orderquery.html" class="order-status">Order Status</a>
        <a href="contact.html">Contact Us</a>
    </div>
</div>
</div>
</div>
</div>

<div class="header-top" id="promotion_count_down" style="display: none">
    <div class="container">
        <div class="row hidden-xs">
            <div class="col-xs-4">
            </div>
            <div class="col-xs-4">
                <div class="site-header-center">
                        <span>
                            <a href="javascript:;">
                                <span class="font-regular" id="count_down"></span>
                            </a>
                        </span>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container logowrap">
<div class="row">
<div class="col-xs-4 col-sm-2 col-md-4 col-lg-4">
    <!-- site header logo -->
    <!-- site header logo -->
    <h2 id="site-logo">
        <a href="index.html" class="patpat-logo">
            <img src="https://img.patpat.com/assets/img/logo_1.png" alt="PatPat Logo"/>
            <span class="hidden-xs hidden-sm logo-line"></span>
            <span class="hidden-xs hidden-sm logo-mom">DAILY DEALS FOR MOMS &amp; KIDS</span>
        </a>
    </h2>
    <!-- site header logo /-->                                        <!-- site header logo /-->
</div>

<!-- site header search bar -->
<div class="col-sm-4 col-md-3 col-lg-4 top-search-wrap">
    <!-- site header search -->
    <form method="get" enctype="multipart/form-data" id="keyword_search" name="keyword_search" action="/search">
        <div id="site-header-search">
            <div id="search-inner">
                <input type="search" name="keyword" placeholder="Search" class="form-control form-control-search"
                       autocomplete="off" id="keyword"/>

                <div class="search-pro-list">
                    <i>Popular Searches</i>
                    <ul>
                    </ul>
                </div>
            </div>
            <button id="site-header-search-btn" class="hidden-xs">
                <em class="icon-search-white">
                </em>
                <span class="sr-only">Submit</span>
            </button>
            <button type="button" id="top-search-close-btn" class="visible-xs"><img
                    src="https://img.patpat.com/assets/img/close_cart@3x.png" alt=""></button>
            <div class="search-down-con" id="hotwords">
                <div class="search-down-con1">
                    <ul class="search-downnav-ulfir" id="hotwords_fields">

                    </ul>
                </div>

            </div>
            <div class="search-default">
                <strong>POPULAR SEARCHES</strong>

                <div class="default-list"></div>

            </div>
            <div class="default-bg"></div>
        </div>
    </form>
    <!-- site header search /-->

    <script>
        $(function () {
            $('#site-header-search-btn').click(function () {
                var keyword = $("#keyword").val().replace(/(^\s*)|(\s*$)/g, '');
                if (keyword != '') {
                    $("#keyword_search").submit();
                } else {
                    return false;
                }
            });

            $('#keyword').bind('input propertychange', function () {
                var keywords = $(this).val();
                $.ajax({
                    method: "post",
                    url: "/hotwords/search",
                    data: {"_token": "CvbgcAQwvjJAPOS289tLg0AVbsZr64wtY5G7wkOB", "words": keywords},
                    success: function (data) {
                        var res = JSON.parse(data);
                        var html = "";
                        if (res['status'] == true) {
                            html += "<div class='search-result'>";
                            var activityList = res.activity,
                                contentList = res.content;
                            if (activityList.length != 0) {
                                html += "<div class='search-activity'><a href=" + activityList["url"] + ">";
                                html += "<span><img src=" + activityList["img"] + "></span>";
                                html += "<p>" + activityList["title"] + "</p>";
                                html += "</a></div>";
                            }
                            html += "<div class='search-list'>";
                            for (contentText in contentList) {
                                html += "<a href='/search?keyword=" + contentList[contentText] + "'><li class=\"item\">";
                                html += contentList[contentText];
                                html += "</li></a>";
                            }
                            html += "</div></div>";
                        }
                        $("#hotwords_fields").html(html);
                        if ($(".search-list").html() == "" && $(".search-activity").length == 0) {
                            $(".search-result").hide();
                        }
                        if (keywords.length == 0) {
                            $("#hotwords_fields").empty();
                        }
                    }
                });
                $(".search-down-con1").show();
            });
            // 热门搜索词
            var hot_search_words = [{"words": "mom and me"}, {"words": "Yoga Pants"}, {"words": "Dresses"}, {"words": "Mermaid swimsuit"}, {"words": "daddy and me"}, {"words": "Diaper"}, {"words": "Swimsuit"}, {"words": "Jumpsuit"}]
            var html = "";
            var keyHost = window.location.host;
            for (key in hot_search_words) {
                html += '<li>';
                html += '<a href="https://' + keyHost + '/search?keyword=' + hot_search_words[key]["words"] + '">' + hot_search_words[key]["words"] + '</a>';
                html += '</li>'
            }
            $(".search-pro-list ul").html(html);

            $("#wap-search-close").on("click", function () {
                $(this).siblings(".search-box").find("input").val("");
                $(this).siblings(".search-box").find("input").focus();
                $(".search-down-con1").hide();
                $(".search-default").show();
                searchList.show();
                $("#hotwords_fields").empty();
            });

            $(".cancel").click(function () {
                $("#top-search-wrap").slideUp();
                $(".search-box").find("input").val("");
                $(".search-pro-list").show();
                $("#wap-top-search").removeClass("wap-top-search-click");
                $(".search-down-con1").hide();
                $("#hotwords_fields").empty();
                $("body").unbind("touchmove");
            });

            // 关键词优化开始
            var keywordPro = $("#keyword"),
                searchList = $(".search-pro-list");
            var boxWidth = keywordPro.width() + 3;
            //  获取焦点
            keywordPro.focus(function () {
                if ($(window).width() > 767) {
                    searchList.slideDown(200);
                }
                if ($(this).val().length > 0) {
                    searchList.hide();
                }
                // 输入的时val()大于0推荐搜索隐藏
                $(this).keyup(function () {
                    if ($(this).val().length > 0) {
                        searchList.hide();
                        $("#hotwords").show();
                        $(".search-default").hide();
                    } else {
                        searchList.show();
                        $("#hotwords").hide();
                        $(".search-default").show();
                    }
                });
//            if(!searchList.is(":hidden") ){
//                if($("html").hasClass("country-ar")){
//                    $(".form-control").css({
//                        borderBottomRightRadius:"0px"
//                    });
//                }else{
//                    $(".form-control").css({
//                        borderBottomLeftRadius:"0px"
//                    });
//                }
//            }
            }).blur(function () {
                if ($(window).width() > 767) {
                    setTimeout(function () {
                        searchList.hide();
                        $("#hotwords").hide();
                    }, 230);
                }
//            if( $("#hotwords").is(":hidden") ){
//                setTimeout(function(){
//                    if($("html").hasClass("country-ar")){
//                        $(".form-control").css({
//                            borderBottomRightRadius:"5px"
//                        })
//                    }else{
//                        $(".form-control").css({
//                            borderBottomLeftRadius:"5px"
//                        })
//                    }
//                },230)
//            }
            });
            searchList.css({
                width: boxWidth
            });
            $("#hotwords_fields").css({
                width: boxWidth
            });
            //  end
        });


    </script>
</div>

<!-- site header icons /-->
<?php $this->widgets->topRightMenu() ?>


</div>
<!-- mobile site header  menu toggle  /-->
<!-- mobile site header  menu  /-->
<button type="button" class="navbar-toggle visible-xs navbar-custom navbar-toggle-dy" id="menu-mobile-open">
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
</button>
<div class="clearfix"></div>
<!-- mobile site header  menu  /-->        <!-- mobile site header  menu toggle  /-->
</div>
</header>

<!-- site header -->

<!-- site navigation -->
<!-- site nav -->
<nav class="navbar navbar-default navbar-static-top" id="site-nav">
    <div class="container category-nav-container">
        <div class="category-nav">
            <div class="category-nav-inner category-nav-inner-newarrivals">
                <a href="new-arrivals" class="nav-tabs-js" id="nav-new-arrivals"><span class="borderC"></span>New
                    Arrivals<em class="borderB"></em></a>

                <div class="category-list"></div>
            </div>
            <div class="category-nav-inner category-nav-inner-flash">
                <a href="flashsale/event.html" class="nav-tabs-js" id="nav-flash-sale"><span class="borderC"></span>Flash
                    Sale<em
                        class="borderB"></em></a>

                <div class="category-list"></div>
            </div>

            <div class="category-nav-inner category-nav-inner-category">
                <a href="category/Baby-Toddlers.html" content="nofollow" class="nav-tabs-js" id="category27">
                    <strong>Baby &amp; Toddlers</strong>
                    <i>2T-4T</i>
                    <em class="borderB"></em>
                </a>

                <div class="category-list">
                </div>
            </div>
            <div class="category-nav-inner category-nav-inner-category">
                <a href="category/Kids.html" content="nofollow" class="nav-tabs-js" id="category28">
                    <strong>Kids</strong>
                    <i>2T-4T</i>
                    <em class="borderB"></em>
                </a>

                <div class="category-list">
                </div>
            </div>
            <div class="category-nav-inner category-nav-inner-category">
                <a href="category/Women.html" content="nofollow" class="nav-tabs-js" id="category29">
                    <strong>Women</strong>
                    <i>2T-4T</i>
                    <em class="borderB"></em>
                </a>

                <div class="category-list">
                </div>
            </div>
            <div class="category-nav-inner category-nav-inner-category">
                <a href="category/Home-Storage.html" content="nofollow" class="nav-tabs-js" id="category26">
                    <strong>Home &amp; Storage</strong>
                    <i>2T-4T</i>
                    <em class="borderB"></em>
                </a>

                <div class="category-list">
                </div>
            </div>

            <div class="category-nav-inner"><a href="clearance.html" class="nav-tabs-js" id="nav-clearance"><span
                        class="borderC"></span>Clearance<em class="borderB"></em></a>
            </div>

        </div>
        <div class="direction visible-sm"></div>
    </div>
</nav>
<!-- site nav -->

<script>
$(function () {
    /*new arrivals*/
    $("#nav-new-arrivals").one("mouseover", function () {
        var html = '';
        html += '<div class="category-list-content arrivals">'
        + ''
        + '<div class="category-list-left">'
        + '<ul class="category-list-left-one">'
        + ''
        + '<li class="ss-menu-list-item">'
        + '<a href="<?php echo $this->config->domain ?>/new-arrivals/Baby-&amp;-Toddlers">Baby &amp; Toddlers</a>'
        + ''
        + '</li>'
        + ''
        + '<li class="ss-menu-list-item">'
        + '<a href="<?php echo $this->config->domain ?>/new-arrivals/Kids">Kids</a>'
        + ''
        + '</li>'
        + ''
        + '<li class="ss-menu-list-item">'
        + '<a href="<?php echo $this->config->domain ?>/new-arrivals/Women">Women</a>'
        + ''
        + '</li>'
        + ''
        + '<li class="ss-menu-list-item">'
        + '<a href="<?php echo $this->config->domain ?>/new-arrivals/Home-&amp;-Storage">Home &amp; Storage</a>'
        + ''
        + '</li>'
        + ''
        + '</ul>'
        + ''
        + '</div>'
        + ''
        + '<div class="category-list-right">'
        + '<div class="list-right-big">'
        + '<a href="/new-arrivals/Baby">'
        + '<img src="https://img.patpat.com/web_index_diy/582d60c3d0e39/1479368899.jpg" alt="">'
        + '<div class="big-name">'
        + '<p class="font-medium"></p>'
        + '<p class="font-black">NEW ARRIVALS</p>'
        + '</div>'
        + '<div class="view-all">VIEW ALL &gt;</div>'
        + '</a>'
        + '</div>'
        + ''
        + ''
        + ''
        + '<div class="list-right-small">'
        + '<a href="<?php echo $this->config->domain ?>/product/Mermaid-Princess-Colorful-Swimsuit-for-Girls3pc-set.html?color=Green">'
        + '<img src="https://img.patpat.com/Product/25082/C-ZL-001-00005-001.jpg/1490603595.jpg/350x350" alt="">'
        + '<p>Mermaid Swimsuit</p>'
        + '</a>'
        + '</div>'
        + ''
        + ''
        + '<div class="list-right-small">'
        + '<a href="<?php echo $this->config->domain ?>/product/Toddler-Girls-Plaid-Button-Down-Dress-with-Ribbon-Tie-in-Beige.html?color=Beige">'
        + '<img src="https://cdn.patpat.com/Product/33025/K-OF-001-00001-001-10.jpg/1490268355.jpg/350x350" alt="">'
        + '<p>Plaid Dress</p>'
        + '</a>'
        + '</div>'
        + ''
        + ''
        + '<div class="list-right-small">'
        + '<a href="<?php echo $this->config->domain ?>/product/Sweet-Mouse-Tee-and-Skirt-Set-for-Toddler-Girls.html?color=Pink">'
        + '<img src="https://cdn.patpat.com/Product/40159/TAOBAO-YC-001-00003-001.jpg/1490947785.jpg/350x350" alt="">'
        + '<p>Tee &amp; Skirt Set</p>'
        + '</a>'
        + '</div>'
        + ''
        + ''
        + '</div>'
        + '</div>';
        $(this).siblings(".category-list").append(html);
    });
    /*flash sale*/
    $("#nav-flash-sale").one("mouseover", function () {
        var html = '';
        html += '<div class="category-list-content row flash_sale">'
        + ''
        + '<div class="col-sm-4">'
        + '<article class="box-product alt alt2 list-flash-con">'
        + '<a href="<?php echo $this->config->domain ?>/Flash-Sale/event/Sweet-Princess-Dress-for-Girls-20338.html" class="img" style="width:100%;">'
        + '<img src="https://img.patpat.com/events/20302/58aea9355736b.jpg/750x340"  data-original="https://img.patpat.com/events/20302/58aea9355736b.jpg/750x340" alt="event" class="img-responsive center-block falsh-img-margin"/>'
        + ' <span class="flash-end-time"><p><img src="https://img.patpat.com/assets/img/icon/flash.png" alt="">Ends in 20 days</p></span>'
        + '</a>'
        + '<div class="caption">'
        + '<h2 class="heading font-regular"><a href="" class="link-black">Sweet Princess Dress for Girls</a></h2>'
        + ' <a href="<?php echo $this->config->domain ?>/Flash-Sale/event/Sweet-Princess-Dress-for-Girls-20338.html" class="price" style="color:#444">Starting from <span class=\'text-primary\'>$2.99</span></a>'
        + '</div>'
        + '</article>'
        + '</div>'
        + ''
        + '<div class="col-sm-4">'
        + '<article class="box-product alt alt2 list-flash-con">'
        + '<a href="<?php echo $this->config->domain ?>/Flash-Sale/event/Darling-Mom-and-Me-Look-21104.html" class="img" style="width:100%;">'
        + '<img src="https://img.patpat.com/Event/21090/58fb236777c22/1492853607.jpg/750x340"  data-original="https://img.patpat.com/Event/21090/58fb236777c22/1492853607.jpg/750x340" alt="event" class="img-responsive center-block falsh-img-margin"/>'
        + ' <span class="flash-end-time"><p><img src="https://img.patpat.com/assets/img/icon/flash.png" alt="">Ends in 9 days</p></span>'
        + '</a>'
        + '<div class="caption">'
        + '<h2 class="heading font-regular"><a href="" class="link-black">Darling Mom and Me Look</a></h2>'
        + ' <a href="<?php echo $this->config->domain ?>/Flash-Sale/event/Darling-Mom-and-Me-Look-21104.html" class="price" style="color:#444">Starting from <span class=\'text-primary\'>$6.99</span></a>'
        + '</div>'
        + '</article>'
        + '</div>'
        + ''
        + '<div class="col-sm-4">'
        + '<article class="box-product alt alt2 list-flash-con">'
        + '<a href="http://www.patpat.com/flashsale/event"  style="width:100%;" class="img">'
        + '<img src="https://img.patpat.com/Test/web_index_diy/57a9a0bd2ce20/1470734525.jpg"  data-original="https://img.patpat.com/Test/web_index_diy/57a9a0bd2ce20/1470734525.jpg" alt="event" class="img-responsive center-block falsh-img-margin"/>'
        + '</a>'
        + '<a href="http://www.patpat.com/flashsale/event" class="amazing-more">MORE AMAZING DEALS &gt;</a>'
        + '</article>'
        + '</div>'
        + '</div>';
        $(this).siblings(".category-list").append(html);
    });
    /*category*/
    var categoriesData = [{
        "id": 27,
        "name": "Baby & Toddlers",
        "sort_order": 0,
        "product_categories": "[845,846,848,849,850,851,853,854,855,856,857,858,860,861,862,863,864,865,866,867,868,869,870,872,873,875,876,877,878,881,882,884,885,886,887,889,890,891,892,893,894,895,896,897,898,900,901,903,904,905,907,908,909,911,912,913,914,915,918,919,920,921,922,923,924,925,926,927,928]",
        "banner": "http:\/\/patpatdev.s3.amazonaws.com\/mall_category\/Baby%2520%2526%2520Toddlers\/1484106517.png",
        "en_name": "Baby & Toddlers",
        "son_categories": [{
            "category_id": 843,
            "name": "Baby & Toddler Girl",
            "link": "https:\/\/www.patpat.com\/category\/Baby-Toddlers\/Baby-Toddler-Girl.html"
        }, {
            "category_id": 879,
            "name": "Baby & Toddler Boy",
            "link": "https:\/\/www.patpat.com\/category\/Baby-Toddlers\/Baby-Toddler-Boy.html"
        }, {
            "category_id": 906,
            "name": "Baby & Toddler Gear",
            "link": "https:\/\/www.patpat.com\/category\/Baby-Toddlers\/Baby-Toddler-Gear.html"
        }, {
            "category_id": 916,
            "name": "Diapering",
            "link": "https:\/\/www.patpat.com\/category\/Baby-Toddlers\/Diapering.html"
        }],
        "hot_categories_id": [],
        "category_image": "https:\/\/img.patpat.com\/web_index_diy\/582d612371a99\/1479368995.jpg",
        "url": "https:\/\/www.patpat.com\/category\/Baby-Toddlers.html",
        "category_href": "\/category\/Baby-Toddlers.html",
        "category_words": "All Baby Needs",
        "products": [{
            "hot_product_img_url": "https:\/\/cdn.patpat.com\/Product\/40157\/TAOBAO-YC-002-00001-001.jpg\/1491031936.jpg\/350x350",
            "hot_product_href": "https:\/\/www.patpat.com\/product\/Ruffled-Sleeveless-Romper-for-Baby-and-Toddler-Girls.html?color=Blue",
            "hot_product_title": "Ruffled Romper",
            "hot_product_subtitle": ""
        }, {
            "hot_product_img_url": "https:\/\/cdn.patpat.com\/Product\/40352\/1688-CH-001-00020-001.jpg\/1491817588.jpg\/350x350",
            "hot_product_href": "https:\/\/www.patpat.com\/product\/Angel-Wings-Tutu-One-piece-Swimsuit-in-Pink-for-Toddler-Girls.html?event_id=21001",
            "hot_product_title": "Little Angle Swimsuit",
            "hot_product_subtitle": ""
        }, {
            "hot_product_img_url": "https:\/\/cdn.patpat.com\/Product\/40420\/1688-HZMC-001-00004-001.jpg\/1491985264.jpg\/350x350",
            "hot_product_href": "https:\/\/www.patpat.com\/product\/HOT-Plaid-Sleeveless-Top-in-Green-for-Baby-and-Toddler-Girls.html",
            "hot_product_title": "Adorable in Plaid",
            "hot_product_subtitle": ""
        }]
    }, {
        "id": 28,
        "name": "Kids",
        "sort_order": 1,
        "product_categories": "[932,933,934,935,936,938,939,940,941,942,943,945,946,947,948,949,950,951,952,953,954,955,956,958,959,961,962,964,965,966,967,970,971,972,973,975,976,977,978,979,980,981,982,983,984,985,987,988,990,991,992]",
        "banner": "http:\/\/patpatdev.s3.amazonaws.com\/mall_category\/Kids\/1484106561.png",
        "en_name": "Kids",
        "son_categories": [{
            "category_id": 930,
            "name": "Girl",
            "link": "https:\/\/www.patpat.com\/category\/Kids\/Girl.html"
        }, {"category_id": 968, "name": "Boy", "link": "https:\/\/www.patpat.com\/category\/Kids\/Boy.html"}],
        "hot_categories_id": [],
        "category_image": "https:\/\/img.patpat.com\/Test\/web_index_diy\/57a9a1e5bfb9b\/1470734821.png",
        "url": "https:\/\/www.patpat.com\/category\/Kids.html",
        "category_href": "\/category\/Kids.html",
        "category_words": "For Your Kids",
        "products": [{
            "hot_product_img_url": "https:\/\/cdn.patpat.com\/Product\/38178\/R-1688I-KLM-001-00058-022.jpg\/1489808079.jpg\/350x350",
            "hot_product_href": "https:\/\/www.patpat.com\/product\/Vintage-Sleeveless-Floral-Dress-for-Toddlers-and-Girls.html?color=Dark+Blue",
            "hot_product_title": "Vintage Dress",
            "hot_product_subtitle": ""
        }, {
            "hot_product_img_url": "https:\/\/cdn.patpat.com\/Product\/40346\/1688-CH-001-00014-001.jpg\/1491817567.jpg\/350x350",
            "hot_product_href": "https:\/\/www.patpat.com\/product\/Vintage-Polka-Dotted-Little-Gal-Two-piece-Swimsuit-in-Red-for-Toddler-Girl.html?event_id=21001",
            "hot_product_title": "Polka Dotted Swimsuit",
            "hot_product_subtitle": ""
        }, {
            "hot_product_img_url": "https:\/\/cdn.patpat.com\/Product\/38430\/1688C-HS-001-00142-001.jpg\/1488010555.jpg\/350x350",
            "hot_product_href": "https:\/\/www.patpat.com\/product\/Stylish-Ripped-Denim-Pants-for-Baby-Toddler-Boys.html",
            "hot_product_title": "Pre-washed Jeans",
            "hot_product_subtitle": ""
        }]
    }, {
        "id": 29,
        "name": "Women",
        "sort_order": 2,
        "product_categories": "[1069,1071,1072,1073,1074,1076,1077,1078,1079,1080,1081,1083,1084,1085,1086,1087,1089,1090,1091,1092,1094,1095,1096,1098,1099,1100,1102,1103,1104,1105,1107,1108,1109,1110,1111,1112,1114,1115,1116,1118,1119,1120,1121,1122,1123,1124,1125,1127,1128,1129,1130,1131,1132,1134,1135]",
        "banner": "http:\/\/patpatdev.s3.amazonaws.com\/mall_category\/Women\/1484106588.png",
        "en_name": "Women",
        "son_categories": [{
            "category_id": 1068,
            "name": "Clothing",
            "link": "https:\/\/www.patpat.com\/category\/Women\/Clothing.html"
        }, {
            "category_id": 1106,
            "name": "Accessories",
            "link": "https:\/\/www.patpat.com\/category\/Women\/Accessories.html"
        }, {
            "category_id": 1113,
            "name": "Jewelry",
            "link": "https:\/\/www.patpat.com\/category\/Women\/Jewelry.html"
        }, {
            "category_id": 1117,
            "name": "Bags",
            "link": "https:\/\/www.patpat.com\/category\/Women\/Bags.html"
        }, {
            "category_id": 1125,
            "name": "Watches & Sunglasses",
            "link": "https:\/\/www.patpat.com\/category\/Women\/Watches-Sunglasses.html"
        }, {
            "category_id": 1126,
            "name": "Beauty",
            "link": "https:\/\/www.patpat.com\/category\/Women\/Beauty.html"
        }, {
            "category_id": 1133,
            "name": "Health Care",
            "link": "https:\/\/www.patpat.com\/category\/Women\/Health-Care.html"
        }],
        "hot_categories_id": [],
        "category_image": "https:\/\/img.patpat.com\/Test\/web_index_diy\/57a9a2660a81f\/1470734950.png",
        "url": "https:\/\/www.patpat.com\/category\/Women.html",
        "category_href": "\/category\/Women.html",
        "category_words": "Trendy Styles",
        "products": [{
            "hot_product_img_url": "https:\/\/cdn.patpat.com\/Product\/38026\/T-RX-001-00111.jpg\/1487406589.jpg\/350x350",
            "hot_product_href": "https:\/\/www.patpat.com\/product\/Mom-and-Me-Matching-Striped-Maxi-Dress-in-Crimson-Price-varies-by-size.html",
            "hot_product_title": "Mom and Me",
            "hot_product_subtitle": ""
        }, {
            "hot_product_img_url": "https:\/\/cdn.patpat.com\/Product\/38571\/1688C-SH-003-00065.jpg\/1488191736.jpg\/350x350",
            "hot_product_href": "https:\/\/www.patpat.com\/product\/Boss-Short-Sleeve-Matching-Tee-in-White-Price-Varies-by-Size.html",
            "hot_product_title": "Matching Tee",
            "hot_product_subtitle": ""
        }, {
            "hot_product_img_url": "https:\/\/cdn.patpat.com\/Product\/12394\/I-MY-002-00044-001.jpg\/1461315824.jpg\/350x350",
            "hot_product_href": "http:\/\/www.patpat.com\/product\/Royal-Golden-Synthetic-Hair-Brush-Set-Soft-Foundation-and-Eyeshadow-Brushes-Kit-with-Black-Case-12pc-set.html",
            "hot_product_title": "Soft Makeup Brushes Set",
            "hot_product_subtitle": ""
        }]
    }, {
        "id": 26,
        "name": "Home & Storage",
        "sort_order": 3,
        "product_categories": "[1054,1055,1056,1057,1058,1060,1061,1062,1063,1064,1065,1066]",
        "banner": "http:\/\/patpatdev.s3.amazonaws.com\/mall_category\/Home%2520%2526%2520Storage\/1484106466.png",
        "en_name": "Home & Storage",
        "son_categories": [{
            "category_id": 1053,
            "name": "Storage & Organizers",
            "link": "https:\/\/www.patpat.com\/category\/Home-Storage\/Storage-Organizers.html"
        }, {
            "category_id": 1057,
            "name": "Home D\u00e9cor",
            "link": "https:\/\/www.patpat.com\/category\/Home-Storage\/Home-D%C3%A9cor.html"
        }, {
            "category_id": 1058,
            "name": "Wall D\u00e9cor",
            "link": "https:\/\/www.patpat.com\/category\/Home-Storage\/Wall-D%C3%A9cor.html"
        }, {
            "category_id": 1059,
            "name": "Electrical Accessories",
            "link": "https:\/\/www.patpat.com\/category\/Home-Storage\/Electrical-Accessories.html"
        }, {
            "category_id": 1063,
            "name": "Kitchen & Dinning",
            "link": "https:\/\/www.patpat.com\/category\/Home-Storage\/Kitchen-Dinning.html"
        }, {
            "category_id": 1064,
            "name": "Bed & Bath",
            "link": "https:\/\/www.patpat.com\/category\/Home-Storage\/Bed-Bath.html"
        }, {
            "category_id": 1065,
            "name": "Outdoors & Sports",
            "link": "https:\/\/www.patpat.com\/category\/Home-Storage\/Outdoors-Sports.html"
        }, {
            "category_id": 1066,
            "name": "Stationery",
            "link": "https:\/\/www.patpat.com\/category\/Home-Storage\/Stationery.html"
        }],
        "hot_categories_id": [],
        "category_image": "https:\/\/img.patpat.com\/Test\/web_index_diy\/57a9a39a51098\/1470735258.png",
        "url": "https:\/\/www.patpat.com\/category\/Home-Storage.html",
        "category_href": "\/category\/Home-Storage.html",
        "category_words": "Household Essentials",
        "products": [{
            "hot_product_img_url": "https:\/\/cdn.patpat.com\/Product\/33677\/1688I-XL-005-00013-001.jpg\/1474529792.jpg\/350x350",
            "hot_product_href": "http:\/\/www.patpat.com\/product\/Blue-Sky-and-White-Clouds-Double-Layer-Hands-Free-Reversible-Umbrella.html",
            "hot_product_title": "Sky C-Handle Umbrella",
            "hot_product_subtitle": ""
        }, {
            "hot_product_img_url": "https:\/\/cdn.patpat.com\/Product\/16853\/1688I-WC-001-00014.jpg\/1451476371.jpg\/350x350",
            "hot_product_href": "http:\/\/www.patpat.com\/product\/Simple-&-Practical-Linen-Laundry-Hamper-Set-3pc-set.html",
            "hot_product_title": "Household Storage",
            "hot_product_subtitle": ""
        }, {
            "hot_product_img_url": "https:\/\/cdn.patpat.com\/Product\/17304\/1688I-LF-002-00016-4.jpg\/1451994378.jpg\/350x350",
            "hot_product_href": "https:\/\/www.patpat.com\/product\/Adorable-Panda-Light-Lamp.html",
            "hot_product_title": "Panda Light Lamp",
            "hot_product_subtitle": ""
        }]
    }];
    $(".category-nav-inner-category").one("mouseover", function () {
        var index = $(this).index() - 2;
        var html = '';
        html += '<div class="category-list-content">';
        var sonCategory = categoriesData[index].son_categories;
        var sonCategoryOne = sonCategory.slice(0, 6),
            sonCategoryTwo = sonCategory.slice(6);
        if (sonCategory.length > 0) {
            html += '<div class="category-list-left">';
            html += '<ul class="category-list-left-one">';
            for (var i = 0; i < sonCategoryOne.length; i++) {
                html += '<li class="ss-menu-list-item">';
                html += '<a href="' + sonCategoryOne[i].link + '">' + sonCategoryOne[i].name + '</a>';
                html += '</li>';
            }
            html += '</ul>';
            html += '<ul class="category-list-left-two">';
            for (var i = 0; i < sonCategoryTwo.length; i++) {
                html += '<li class="ss-menu-list-item">';
                html += '<a href="' + sonCategoryTwo[i].link + '">' + sonCategoryTwo[i].name + '</a>';
                html += '</li>';
            }
            html += '</ul>';
            html += '</div>';
        }
        html += '<div class="category-list-right">';
        html += '<div class="list-right-big">';
        html += '<a href="' + categoriesData[index].category_href + '">';
        html += '<img src="' + categoriesData[index].category_image + '" alt="">';
        html += '<div class="big-name"><p class="font-medium">' + categoriesData[index].name + '</p>';
        html += '<p class="font-black">' + categoriesData[index].category_words + '</p></div>';
        html += '<div class="view-all">VIEW ALL &gt;</div>';
        html += '</a></div>';
        var categoryProducts = categoriesData[index].products;
        var categoryProductsNum = categoryProducts.slice(0, 3);
        if (categoryProductsNum.length > 0) {
            for (var i = 0; i < categoryProductsNum.length; i++) {
                html += '<div class="list-right-small">';
                html += '<a href="' + categoryProductsNum[i].hot_product_href + '">';
                html += '<img src="' + categoryProductsNum[i].hot_product_img_url + '" alt="">';
                html += '<p>' + categoryProductsNum[i].hot_product_title + '</p>';
                html += '</a></div>';
            }
        }
        html += '</div></div>';
        $(this).children("a").siblings(".category-list").append(html);
    });

    $("body").on("touchend click", ".ss-menu-list-item a", function () {
        var arrivalsName = $(this).text();
        sessionStorage.setItem("arrivalsNames", arrivalsName);
    });
    $(".category-nav-inner-newarrivals").on("click", function () {
        sessionStorage.removeItem("arrivalsNames");
    });


    var navMentSize = ['NB-5T', '6-13']
    var navMenu = $(".category-nav-inner");
    for (var i = 0; i < navMenu.length; i++) {
        if (i > 1 && i < 4) {
            navMenu.eq(i).addClass("nav-pro-menu");
            navMenu.eq(i).find("i").text(navMentSize[i - 2])
        }
        ;
    }
    ;
    $(".nav-pro-menu").hover(function () {
        $(this).find("strong").stop().animate({
            top: "-8px"
        })
        $(this).find("i").stop().animate({
            bottom: "15px"
        })
    }, function () {
        $(this).find("strong").stop().animate({
            top: "4px"
        })
        $(this).find("i").stop().animate({
            bottom: "-14px"
        });
    });
});
</script>

<!-- site navigation -->


<script>
    $(function () {
        $("#wap-top-search").on("click", function () {
            $("#top-search-wrap").slideToggle();
            $(this).toggleClass("wap-top-search-click");
            if ($(this).hasClass("wap-top-search-click")) {
                $("input[name='keyword']").focus();
                $("body").bind("touchmove", function (event) {
                    event.preventDefault();
                });

            } else {
                $("input[name='keyword']").blur();
                $("body").unbind("touchmove");
            }
            $(".filter-btn a.tab-btn").find("em").removeClass("click");
            $(".filter-btn a.tab-btn").parent().find(".filter-show").fadeOut();
            $(".category-show-results").slideDown();
            $(".search-show-results").slideDown();
            $("#diy-banner-hide").slideDown();
        });

        var topCash = $(".top-cash");
        topCash.hover(function () {
            $(this).children(".cash").show();
        }, function () {
            $(this).children(".cash").hide();
        });
    })
</script>
